version: "3.8"

services:
  coursework-pg:
    container_name: coursework-pg
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - coursework_data:/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  coursework-app:
    container_name: coursework-app
    build:
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      coursework-pg:
        condition: service_healthy

volumes:
  coursework_data:
